### ISSUE TITLE
guild_id list Data type.

### ISSUE THREAD

**Issue by kangyoolee** [dico-api/dico-interaction#6]
pycord 같은 경우 guild_id를 list로 지원해 여러개의 길드에 테스트를 해볼 수 있습니다.
dico-interaction 에서 slash_command, context_menu 등에서 guild_id는 list 자료형은 지원하지 않고 int,str 값 하나만 지원합니다.
여러 길드에서 테스트를 해보려면 guild_id를 list 자료형을 지원하도록 변경해야 한다고 생각합니다.

In the case of pycord, you can test multiple guilds by supporting build_id as a list.
In deco-interaction, in slash_command, context_menu, etc., build_id does not support list material types, but only int,str values.
In order to test in multiple guilds, I think we need to change the guild_id to support the list material type.

**Comment by eunwoo1104** [comment]
Implemented and will be released on 0.0.7
